author: Bong's blog
description: 개발공부 정리 블로그
keyword: Java, Spring, SQL, JavaScript
favicon: 

excerpt_link: 더보기

menu:
 Home: /
 Tags: /tags/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment, uyan or disqus

comment: 

# gitment config
gitment_owner: 
gitment_repo: 
gitment_oauth_id: 
gitment_oauth_secret: 

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 

# disqus config
disqus_shortname: 

about: 
  banner: 
  avatar: https://avatars3.githubusercontent.com/u/46507664?s=400&u=63bda722725fcd9404cf2779c7769ba133c76172&v=4
  description: "안녕하세요. 최용락입니다. <br> 좋은 Back-End 개발자가 되기위해 얻은 지식을 기록하고 있습니다.<br> 본 블로그에서는 Java/Spring/devops를 주로 다루고 있습니다.<br>
  <h2>Experience</h2>
  <a href='http://rsupport.com'>Rsupport</a>  (웹개발 1팀) : 2019.06.17 ~ 재직중<br>
  <a href='http://edu.kosta.or.kr'>KOSTA</a>  (Web Framework 개발자 양성 과정) : 2018.10.29 ~ 2019.02.28<br>
  <a href='http://secokomos.com/main/main.php'>KOMOS</a>  (설계팀) : 2017.06.04 ~ 2018.05.31 (Steering wheel/wheel cover/wheel cap)<br>
  <h2>Contact</h2><a href='mailto://jipsyer@naver.com'>Email</a> : jipsyer@naver.com<br>
  <a href='https://medium.com/@cyr9210'>Medium</a> : https://medium.com/@cyr9210 "
  github_username: cyr9210
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
